#! /usr/local/env bash
shift \n\
addr1=$0 \n\
shift \n\
addr2=$1 \n\
shift \n\
declare -a OPTIONS \n\
i=0 \n\
while (( "$#" )); do \n\
    OPTIONS[$i]={} \n\
    shift \n\
done \n\
\n\
socat ${OPTIONS[*]} $addr1 $addr2 & \n\
((i=i+1)) \n\
exit 0